export type { DocGetRoot200, DocGetRootError, DocGetRootQueryResponse, DocGetRootQuery } from "./clients/types/DocGetRoot.ts";
export type { ErrorDetail } from "./clients/types/ErrorDetail.ts";
export type { ErrorModel } from "./clients/types/ErrorModel.ts";
export type { HomeGetRoot200, HomeGetRootError, HomeGetRootQueryResponse, HomeGetRootQuery } from "./clients/types/HomeGetRoot.ts";
export type { HomePostSpeak200, HomePostSpeakError, HomePostSpeakMutationRequest, HomePostSpeakMutationResponse, HomePostSpeakMutation } from "./clients/types/HomePostSpeak.ts";
export type { SpeakGetResponseSerializerBody } from "./clients/types/SpeakGetResponseSerializerBody.ts";
export type { SpeakPostRequestSerializerBody } from "./clients/types/SpeakPostRequestSerializerBody.ts";
export type { SpeakPostResponseSerializerBody } from "./clients/types/SpeakPostResponseSerializerBody.ts";
export { docGetRootClient } from "./clients/axios/DocumentationService/docGetRootClient.ts";
export { documentationService } from "./clients/axios/DocumentationService/documentationService.ts";
export { homeGetRootClient } from "./clients/axios/HomeService/homeGetRootClient.ts";
export { homePostSpeakClient } from "./clients/axios/HomeService/homePostSpeakClient.ts";
export { homeService } from "./clients/axios/HomeService/homeService.ts";
export { operations } from "./clients/axios/operations.ts";
export { docGetRoot200Schema, docGetRootErrorSchema, docGetRootQueryResponseSchema } from "./clients/zod/docGetRootSchema.ts";
export { errorDetailSchema } from "./clients/zod/errorDetailSchema.ts";
export { errorModelSchema } from "./clients/zod/errorModelSchema.ts";
export { homeGetRoot200Schema, homeGetRootErrorSchema, homeGetRootQueryResponseSchema } from "./clients/zod/homeGetRootSchema.ts";
export { homePostSpeak200Schema, homePostSpeakErrorSchema, homePostSpeakMutationRequestSchema, homePostSpeakMutationResponseSchema } from "./clients/zod/homePostSpeakSchema.ts";
export { speakGetResponseSerializerBodySchema } from "./clients/zod/speakGetResponseSerializerBodySchema.ts";
export { speakPostRequestSerializerBodySchema } from "./clients/zod/speakPostRequestSerializerBodySchema.ts";
export { speakPostResponseSerializerBodySchema } from "./clients/zod/speakPostResponseSerializerBodySchema.ts";